### ISSUE TITLE
Running Async jobs consecutively

### ISSUE THREAD

**Issue by ixam1** [wildhart/meteor.jobs#14]
In the Docs it says:

> Other jobs of the same type will still run when scheduled while asynchronous jobs are executing.

Am I understanding this correctly, that async jobs will not run consecutively no matter what?

If not how would I go about setting up async jobs that will run consecutively?

I have an expensive async operation using puppeteer, that might get batched and my entire purpose of this package was to run them consecutively.

My Code:

```
Jobs.register({
	async myExpensiveJob() {
		console.log("Start")
		await new Promise((resolve) => setTimeout(resolve, 5000))
		console.log("End")

		this.success()
	},
})

Meteor.methods({
	startExpensiveJob() {
		if (!this.userId || !Roles.userIsInRole(this.userId, "admin"))
			throw new Meteor.Error("no-permission")

		let jobDocId = Jobs.run("myExpensiveJob")._id
		Jobs.execute(jobDocId)
		return jobDocId
	},

})
```

The client will start the job via the Meteor method. If the client starts the job 3 times shortly after another. I get the following output:

```
Start
Start
Start
End
End
End
```

But I want them consecutively:

```
Start
End
Start
End
Start
End
```

Is this possible?

**Also**: I am using `Jobs.execute(jobDocId)` because for some reason the job doesnt run with just `Jobs.run()`, although it should right? Am I doing something wrong?

Thanks for any help in advance!

**Comment by wildhart** [comment]
With the current implementation this is only possible as follows:
- Create the `expensiveJob` as an async job so that it doesn't hold up other types of job - just as you've done above.
- When you want to run the job for a particular id:
  -  (using [`Jobs.collection`](https://github.com/wildhart/meteor.jobs#jobscollection)) look for a pre-existing 'pending' or 'executing' job of the same type.
  - If an existing job is found, add the new id (or path, or whatever parameters you need to run the job) to the `arguments` array and save the job.
  - If an existing job isn't found, schedule the new job with the new id.
- When the job runs, within the job function:
  - make it pop the first id off the parameter array
  - execute the Puppeteer code using the id.
  - when that finishes fetch a fresh parameter list from the job document (in case it's been added to while the Puppeteer code was running).
  - If the parameter list is not empty, repeat the Puppeteer code until the fresh list is empty.

This means that you only ever have one copy of this job running at a time, but other types of job can continue running.

I haven't been able to test this, but this might work:
```
Jobs.register({
	async myExpensiveJob() {
		console.log("Start job");
		let docId = null;
		do {
			// get the next id to operate one, fresh from the latest job arguments
			var freshJobDoc = Jobs.collection.findOne(this.document._id);
			docId = freshJobDoc.arguments[0];
			if (docId) {
				// remove this id from the document
				Jobs.collection.update(this.document._id, {$pop: {arguments: -1}});

				// run the job
				console.log("Start - docId", docId)
				await new Promise((resolve) => setTimeout(resolve, 5000))
				console.log("End - docId", docId)
			}
		} while (docId)
		this.success()
	},
})

Meteor.methods({
	startExpensiveJob(idOfDocumentToOperateOn) {
		if (!this.userId || !Roles.userIsInRole(this.userId, "admin"))
			throw new Meteor.Error("no-permission")

		let jobDoc = Jobs.collection.findOne({name: 'myExpensiveJob', state: {$in: 'executing', 'pending'}});
		if (jobDoc) {
			Jobs.collection.update(jobDoc._id, {$push: {arguments: idOfDocumentToOperateOn}});
		} else {
			jobDoc = Jobs.run('myExpensiveJob', idOfDocumentToOperateOn);
		}
		return jobDoc._id;
	},
```

However, if you can wait a couple of days then I should be able to add an API parameter which prevent async jobs of the same type from running simultaneously.

By the way, you shouldn't need to call `Jobs.execute()` after `Jobs.run()` - the job will be scheduled to run immediately, pending other jobs in the queue.

**Comment by ixam1** [comment]
Thanks for the very fast reply!

Actually that would be awesome if you could add that API parameter. 

Your solution would work, but I´d have to redo my client side, which currently nicely uses the jobs collection to get the progress of the current job. I really like that that was so easy to do. With this workaround, it´d be more complicated. So I´d be glad to wait.

**Comment by ixam1** [comment]
> By the way, you shouldn't need to call `Jobs.execute()` after `Jobs.run()` - the job will be scheduled to run immediately, pending other jobs in the queue.

For some reason its weird when I just use `Jobs.run()` , rarely they get executed immediately, sometimes 10 minutes late and sometimes never. Do you have any idea why that could be happening?

**Comment by wildhart** [comment]
Try version 1.0.14 and add `{awaitSync: true}` as a parameter when you run the job :wink:
```
Jobs.run("myExpensiveJob", {awaitAsync: true});
```

As for the job not running immediately - are you in a single server environment?  If so run:
```
Jobs.Configure({
    setServerId: "MySingleServer",
    ...
});
```
This wont have any effect the first time you run the code, but after that the job queue should start running immediately.  Have a look at [Jobs.Configure()](https://github.com/wildhart/meteor.jobs#jobsconfigure) for the explanation.

**Comment by ixam1** [comment]
Thanks. You are awesome for doing this so quickly! Both problems fixed for me 😄 

You forget to extend the [isConfig](https://github.com/wildhart/meteor.jobs/blob/9f0021513a9ffdd5a287ab2fe386689bf071c11e/jobs.ts#L67) function with awaitAync, so just setting `{awaitAsync: true}` won´t work. As a workaround I just set priority to 1 for now 😉 

Again many thanks!

**Comment by wildhart** [comment]
Well spotted, and nice work-around!  I was also passing an `in` parameter in my tests so `isConfig()` was passing for me.

Try v1.0.15...

**Comment by ixam1** [comment]
Everything works perfect now thanks!

**Comment by wildhart** [comment]
Hi @ixam1,

I realised that I wasn't catching errors within async jobs, which is the case of an `awaitAsync` job would mean no other jobs of that type would run again.  Please update to v1.0.16
